### PR TITLE
Fixed rotation issue on iOS using EXIF Orientation

### PR DESCRIPTION
**Pull request by timbrandin**
Using the newly ported blueimp:javascript-load-image

### CODE REVIEW

**Comment by timbrandin** [comment]
A plus is that we also return a tonne of exif data now from the images.

**Comment by timbrandin** [comment]
Can we get a review on this? :)

**Comment by timbrandin** [comment]
To slow, I'm publishing this as: timbrandin:image-resize-client, tell me when you've reviewed this.

**Comment by satyavh** [comment]
What's going on here, 26 days to review / accept a pull request?

**Comment by aaronthorp** [comment]
yeah, I dont get as much time as i would like to play open source these days, and been overseas for work for past month, will try and have a look at it tonight if i get a chance and push the ver.

**Comment by nathanhornby** [comment]
I'm just looking at using this package - am a little lost as to which fork I should be using. @aaronthorp your position is completely reasonable, life gets in the way - am I better of using @timbrandin 's fork or will that soon become redundant? Anyone able to advise I'm all ears.

**Comment by timbrandin** [comment]
In my opinion you can use my fork, otherwise @aaronthorp could add me as coauthor and I can merge it by myself. :)

**Pull request merged**
